### ISSUE TITLE
Add DevRel resources for ppl who are DevRel-curious

### ISSUE THREAD

**Issue by mary-grace** [devrelcollective/devrelcollective.github.io#3]
We often get applications from people who say that they're interested in learning more about DevRel. While we love these questions and definitely want to do a better job of explaining DevRel to the masses, this Slack isn't the best place for that. It's far more likely that someone will get overwhelmed by the amount of information and the lack of guidance around "how to do DevRel."

Creating a sub-section or child page of the website allows us to provide materials to those are curious about what Developer Relations is and the value that it provides. 

I'm in the process of trying to hook into the Pocket API to automatically pull any articles that I tag as "whatis" to be a resource for people, but we can easily build out the page first with a handful of community favorites. I'd also like the below information displayed either on the main website or somewhere on this child page.

## Why is this an exclusive group?
We feel it’s important for those of us who are pursuing this career to have a private and safe place to talk about our struggles, offer suggestions and congratulations, seek advice, and create professional relationships with others in the industry. As a result, we are limiting access to this group to those who are either actively entrenched in this career or actively pursuing a career shift into Developer Relations. 

If you are actively involved in developer communities or event management, we welcome your input on our public Github repos and appreciate your support! Please let us know if there is anything we can do to support you.

If you are curious about Developer Relations, whether as a potential career path or as a company, please take a look at the resources listed <here> and don’t hesitate to <reach out> if you have any questions.

**Comment by jerdog** [comment]
Alright. If you have already some suggested resources I will add them

**Comment by jerdog** [comment]
For relevancy, here is the documentation from Pocket around retrieving content via their API: https://getpocket.com/developer/docs/v3/retrieve

**Comment by swarnap** [comment]
Some resources:
Ashley's post: https://medium.com/@ashleymcnamara/what-is-developer-advocacy-3a92442b627c
Mary's newsletter: http://devrelweekly.com/
Core competencies of DevRel: https://medium.com/google-developers/the-core-competencies-of-developer-relations-f3e1c04c0f5b

**Comment by jerdog** [comment]
Not so sure that the "Core competencies" is as valid now? That heavily advocates (pun intended, sort of) for DevRel being active developers - and we've had some good conversations recently in #general around that subject. I believe it puts a high bar that's not entirely reachable for some and keeps valid people out of consideration.

**Comment by jerdog** [comment]
Closed via 8681856
