### ISSUE TITLE
Add mentorship form to website

### ISSUE THREAD

**Issue by mary-grace** [devrelcollective/devrelcollective.github.io#31]
Now that we have a mentorship program in place (at least in beta 😅 ) we should be more proactive about letting people know! I'd like to update the website to include the [link to the mentorship form](https://devrelcollective.typeform.com/to/fGYQ75iz) and a quick blurb about what the program is.

**Comment by davidgs** [comment]
If someone has a blurb for me, I can add it in.

**Comment by davidgs** [comment]
moved to new site.
