### ISSUE TITLE
Redo website

### ISSUE THREAD

**Issue by jerdog** [devrelcollective/devrelcollective.github.io#33]
It's high time we have a new website, and work has begun on this. More info to come.

**Comment by jerdog** [comment]
I've started kicking this off with a new repo of mine, using Hugo (https://github.com/jerdog/drc-new-site/pull/1). The first step will be to migrate all current content to the new structure, and then add/adjust where needed.

**Comment by davidgs** [comment]
Well, I currently have some expertise in Hugo so I can jump in and help as much as required. We can even support multiple languages as I now have an auto-translator for Hugo that will translate an entire site. 

I can help with customizing a theme, etc.

**Comment by jerdog** [comment]
> Well, I currently have some expertise in Hugo so I can jump in and help as much as required. We can even support multiple languages as I now have an auto-translator for Hugo that will translate an entire site.
> 
> I can help with customizing a theme, etc.

Sounds good @davidgs - let's try to sync up in the next week and see what needs to happen

**Comment by jerdog** [comment]
David has created a PR which was merged to my repo (https://github.com/jerdog/drc-new-site) and can currently be seen at https://elegant-kilby-ac915a.netlify.app/

**Comment by jerdog** [comment]
New site design is done - next steps will be to add new content, which will be new issues
