### ISSUE TITLE
Request: Submit your favorite DevRel resources

### ISSUE THREAD

**Issue by jerdog** [devrelcollective/devrelcollective.github.io#5]
Our website now has a "DevRel Resources" section, but it's a bit light on the resources.. So we're asking those in the community to help us populate it! Please submit to this Issue your favorite DevRel resource (book, website, etc.) and we'll start adding them... OR... submit a PR with your suggestions!

**Comment by mary-grace** [comment]
The Art of Community by Jono Bacon

(sidenote: not sure if we're wanting to add links or encouraging people to pick up copies at their local stores... thoughts?)

**Comment by jerdog** [comment]
That one is already included. I linked to the website as he provides a free PDF, but certainly could adjust and have a link to both free and paid

**Comment by andypiper** [comment]
This may be of interest - although it's a bit circular :-) my [list of resources for getting started in DevRel](https://gist.github.com/andypiper/7fdb73f9713b7e1f7e5e7ac373f635cb)

**Comment by davidgs** [comment]
closing.
