### ISSUE TITLE
How do we share more DevRel articles on the site?

### ISSUE THREAD

**Issue by mbbroberg** [devrelcollective/devrelcollective.github.io#7]
Discussing architecture. Potentially as someone submits ideas, like in #3 and #4, we curate metadata tags. Architectural discussion led us to think about: 

- **Our Guide to DevRel** - curated list of books, videos, links.
- **Tagged Resources** - curate collection of links in very short articles from someone in the community. Best to show by example here. 

Questions: who's on point for these, and what are their urls.

**Comment by mbbroberg** [comment]
Thinking on the former, `/definitive-guide` would be easy enough and `/tags` would be good for the latter (and thankfully a default in Jekyll).

**Comment by jerdog** [comment]
So if I follow this correctly, since I had to hop off the call, we would essentially start doing blog posts?

**Comment by mbbroberg** [comment]
@jerdog exactly, and then setup the blog page to be tag-driven.

**Comment by jerdog** [comment]
This could be interesting, just wondering how much content we would get? Would we solicit it? Cross-post it?

**Comment by davidgs** [comment]
We could solicit blog posts as PRs to the main site, and merge them in as Blog posts under Hugo. This would be pretty straightforward to set up as part of #33

**Comment by jerdog** [comment]
Yeah the thing that I think we had came to as we discussed this _two and a half_ years ago was how it would differ from what's already out there on Dev.to, personal sites, etc.? I see a bit more value personally in having a better resources section.

**Comment by davidgs** [comment]
Same. Shall we just close this?

**Comment by davidgs** [comment]
closing.
